CREATE TABLE POSTS
    (POSTID INT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(20) NOT NULL,
    BODY VARCHAR(100) NOT NULL);

INSERT INTO POSTS (POSTID , TITLE, BODY) VALUES 
    (1,'10','TEN'),(2,'20','TWENTY'),(3,'30','THIRTY');

CREATE TABLE COMMENTS
    (COMMENTID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BODY VARCHAR(100) NOT NULL,
    POSTID INT,
    CONSTRAINT POSTID_REF FOREIGN KEY (POSTID) REFERENCES POSTS(POSTID) ON DELETE CASCADE ON UPDATE NO ACTION);
     
INSERT INTO COMMENTS (COMMENTID , NAME , EMAIL , BODY , POSTID) VALUES 
    (1,'10name','TEN@email.com' , 'TEN Body' , 1),
    (2,'20name','TWENTY@email.com' , 'TWENTY Body' , 2),
    (3,'20name','TWENTY@email.com' , 'TWENTY Body' , 2),
    (4,'30name','THIRTY@email.com' , 'THIRTY Body' , 3);
 